#!/bin/sh
# MIT License
#
# Copyright (c) 2024 Tony Walker
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


# Selects the default container manager (e.g., Podman).
#
# Podman, Docker, or both may be installed on a system and used almost
# interchangeably. While, Podman does offer compatibility stubs, some may
# want to have both Docker and Podman installed or not install the Docker
# compatibility support for Podman. This script helps in those situations by
# selecting Podman or Docker based on which is installed. This script prefers
# Podman.
#
# One suggestion for using this script is to call it from .bashrc and store
# the result in an environment variable, for example:
#
# ...
# export CONTAINER_MANAGER=$(find-container-manager)
# ...
#
# This variable can then be used to build a container or overridden to change
# the default selected in the .bashrc.


PODMAN_PATH=$(which podman 2> /dev/null)
if [ "$PODMAN_PATH" ]; then
    echo "$PODMAN_PATH"
    exit 0
fi

DOCKER_PATH=$(which docker 2> /dev/null)
if [ "$DOCKER_PATH" ]; then
    echo "$DOCKER_PATH"
    exit 0
fi

# Neither found, so exit with error
echo ""
echo "ERROR: No container manager was found, install Podman or Docker."  >&2
exit 1
